'use client'
import './globals.scss'
import { Inter } from 'next/font/google'
import { CssBaseline, ThemeProvider } from '@mui/material'
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import 'dayjs/locale/es-mx';
import { Suspense } from 'react'


const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Empleado Management</title>
      </head>

        <CssBaseline />
        <body >
        <LocalizationProvider dateAdapter={AdapterDayjs}  adapterLocale="es-mx">
        {children}

        </LocalizationProvider>
        </body>
        
    </html>
  )
}